url: https://citelab.github.io
# baseurl: /agency


# Site settings
title: citélab
email: maheswar@cs.mcgill.ca
description: "Cloud, Internet of Things, and Edge computing research Lab lead by Prof. Maheswaran at McGill University located in Montreal, Canada."


# Projects
research:
  - topic: Cloud & Fogs
    icon: fas fa-cloud
    description: We are investigating cloud & fog architectures for executing tasks with near real-time processing requirements. For example, managing tasks injected from vehicular systems into cloud or edge-based computing backends for processing.

  - topic: Intelligent Internet of Things
    icon: fas fa-laptop
    description: We are working on middleware and programming frameworks for IoT that would self-organize the IoT and edge computing systems for optimal placement of task executions. We are using machine learning for optimizing handover and also data transfer with edge-based IoT.

  - topic: Networking Toolkits
    icon: fas fa-network-wired
    description: We are implementing easy-to-use networking toolkits, high-level toolkits for experimenting with clouds, software-defined networks, and virtual network functions. This work started as a teaching toolkit and is quickly evolving as a research platform into novel distributed cloud architectures combining Clouds, SDN and NFV.

  - topic: Artificial Intelligence & Machine Learning
    icon: fab fa-connectdevelop
    description:


# Team names, titles and social links
team:
  - role: professor
    people:
    - name: Muthucumaru Maheswaran
      info: More info could go here...
      pic: mahes
      social:
        - title: external-link-alt
          url: http://www.cs.mcgill.ca/~maheswar/

  - role: post-doc
    people:
    - name: Sarkhouh Ebrahim 

  - role: phd
    people:
    - name: Fozail Ahmed
    - name: Richboy Echomgbe

  - role: masters
    people:
      - name: Samuel Genois
      - name: Amir Hossein Estiri
      - name: Abhijit Roy
      - name: Mayank Shrivastava
      - name: Nishit Dabi
      - name: Tianzi Yang

  - role: undergraduate
    people:
      - name: Zhelin Xu
      - name: Yuxiang Ma
      - name: Mark Kuhn
      - name: Jianing Xu



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/citelab
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll


# Postal address (add as many lines as necessary)
address:
  - line: muthucumaru.maheswaran@mcgill.ca
  - line: McConnell Engineering Building, Room 224
  - line: 3480 University Street
  - line: Montreal, QC, H3A 2A7 Canada

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - projects
  - publications
